### PR TITLE
fix: fixing `nw.all()` doesn't work in sum_horizontal

### LINKED ISSUE #1071: [Bug]: `nw.all()` doesn't work in `sum_horizontal` if native df is `pd.DataFrame`
### Describe the bug

`nw.all()` doesn't work in `sum_horizontal` if native df is `pd.DataFrame`
It works well for `pl.DataFrame` and it works for `pd.DataFrame` with columns names.

### Steps or code to reproduce the bug

```
import pandas as pd
import polars as pl
import narwhals as nw 

data = {"a": [1, 2, 3], "b": [10, 20, 30]}
df_pd = pd.DataFrame(data)
df_pl = pl.DataFrame(data)

#this works fine
pl_nw = nw.from_native(df_pl)
hor_sum = pl_nw.select(nw.sum_horizontal(nw.all()))
nw.to_native(hor_sum)
a
i64
11
22
33


#this also works fine
pd_nw = nw.from_native(df_pd)
hor_sum = pd_nw.select(nw.sum_horizontal("a", "b"))
nw.to_native(hor_sum)
	a
0	11
1	22
2	33

#this doesn't work
pd_nw = nw.from_native(df_pd)
hor_sum = pd_nw.select(nw.sum_horizontal(nw.all()))
nw.to_native(hor_sum)
	a	b
0	1	10
1	2	20
2	3	30
```

### Expected results

```
pd_nw = nw.from_native(df_pd)
hor_sum = pd_nw.select(nw.sum_horizontal(nw.all()))
nw.to_native(hor_sum)

        a
0	11
1	22
2	33
```

### Actual results

```
pd_nw = nw.from_native(df_pd)
hor_sum = pd_nw.select(nw.sum_horizontal(nw.all()))
nw.to_native(hor_sum)
	a	b
0	1	10
1	2	20
2	3	30
```

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.8.0-45-generic-x86_64-with-glibc2.35

Python dependencies:
     narwhals: 1.8.3
       pandas: 2.2.3
       polars: 1.8.1
         cudf: 
        modin: 
      pyarrow: 16.1.0
        numpy: 2.1.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Cheukting**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [X] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #1071 
- Closes #1071

## Checklist

- [X] Code follows style guide (ruff)
- [X] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

Fixing bug for sum_horizontal (see #1071)

### CODE REVIEW

**Comment by Cheukting** [comment]
@MarcoGorelli we still have to find a way to make it work for Dask, but do you want to have a look at the implementation of `pandas_like` to see if it is what you was thinking?

**Comment by MarcoGorelli** [comment]
yup, thanks @Cheukting ! this is great

if you wanted anything for the sprint, there's a few issues which would be good (#1000, #1004, ...)

i'll just add dask / pyarrow so we can make a release 🚀

**Review by MarcoGorelli — APPROVED** [review]
thanks @Cheukting , and thanks @anopsy for spotting this issue!

**Comment by Cheukting** [comment]
Thanks @MarcoGorelli (ship it!!!!)

**Comment by MarcoGorelli** [comment]
:thinking: why isn't the quokka gif showing

**Comment by MarcoGorelli** [comment]
Ship it!

**Pull request merged**
