### PR TITLE
docs:add docstring series getitem

### LINKED ISSUE #1553: docs: add docstring for Series.__getitem__
We're missing a docstring for Series.__getitem__, let's add one!

### PR DESCRIPTION
**Pull request by TimOsahenru**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues

- Related issue #1553 
- Closes #1553 

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added
- [x] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks, this is off to a good start! did you run `mkdocs serve` and check the output?

**Comment by TimOsahenru** [comment]
Hello @MarcoGorelli can you please help me review this PR again, so it can be merged. Thanks

**Comment by MarcoGorelli** [comment]
thanks - as shown in the screenshot, the bullet points weren't rendering correctly

**Review by MarcoGorelli — APPROVED** [review]
thanks @TimOsahenru

**Pull request merged**
