### PR TITLE
made corrections to expr.filter docstring

### PR DESCRIPTION
**Pull request by brentomagic**

### CODE REVIEW

**Comment by MatthewMec** [comment]
Would it be possible to demonstrate another operand in the example such as == or <?

**Comment by brentomagic** [comment]
> Would it be possible to demonstrate another operand in the example such as == or <?

ok, ya that's possible. Let me work on that.

**Review by ChristianLG2 — CHANGES_REQUESTED** [review]
Thank you for your work on this project. I have a suggestion to improve the clarity and completeness of the docstring for the filter method. Detailed and well-structured docstrings help ensure that our code is understandable and maintainable. Here are my suggestions:

Add Parameters Section to Explicitly describe the parameters, making it clear what inputs are expected.
Add Returns Section to Clearly state what the method returns.

I believe these changes will make the docstring more informative and user-friendly.

**Review by MarcoGorelli — APPROVED** [review]
looks great, thanks @brentomagic , and others for reviews

**Pull request merged**
