### PR TITLE
feat: allow `format=None` in `str.to_datetime`

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [x] Documented the changes

## If you have comments or can explain your changes, please do so below.

~~Opening as draft since~~ (Ok I misscliked) pyarrow is unsupported and may need some discussion for how to achieve it.

For context, this is the snippet in plotly that requires casting to datetime: [process_dataframe_timeline](https://github.com/plotly/plotly.py/blob/7181c4dbdd86400b2b984434e25128507aa8ea69/packages/python/plotly/plotly/express/_core.py#L1780)

### CODE REVIEW

**Review by MarcoGorelli — COMMENTED** [review]
thanks @FBruzzesi !

just a thought - it looks like [here](https://stackoverflow.com/a/76376483/4451315) there's a pure-python solution to inferring a format

maybe, in plotly, they could do something like:
- if it's pandas-like or polars, use `to_datetime` with `format=None`
- else, take the first non-null element, get the format using the solution above, and try to parse using that?

just an idea - not a blocker for this pr anyway!

**Review by MarcoGorelli — APPROVED** [review]

**Comment by FBruzzesi** [comment]
> just a thought - it looks like [here](https://stackoverflow.com/a/76376483/4451315) there's a pure-python solution to inferring a format
> 
> * if it's pandas-like or polars, use `to_datetime` with `format=None`
> * else, take the first non-null element, get the format using the solution above, and try to parse using that?

Shall we consider doing that in narwhals for pyarrow backend and null format? I think it can be a quite common use case for anything related with timeseries.

**Comment by MarcoGorelli** [comment]
yeah sure!

**Pull request merged**
