### PR TITLE
feat: Added `max`, `min`, and `round` to dask backend

### PR DESCRIPTION
**Pull request by mistShard**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #637 
- Closes #

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by anopsy** [comment]
Hi Benji,

I see you’re working on #637 (min,max and round). Before you start, please check if someone else has already taken the task. You can do this by using Ctrl + F to search for the methods you want to work on within the issue. If it’s not taken, add a comment in #637 to indicate that you’ll be working on it. This way, we can avoid any overlap.

**Comment by mistShard** [comment]
@anopsy I apologize for that. I first looked at the issue about 3 days ago and your comment wasn't up yet. However, I should have commented that I would be working on it.

Again, I apologize for that.

**Comment by anopsy** [comment]
no worries, good luck with round!

**Comment by mistShard** [comment]
Thank you. Good luck with the other issues you decide to tackle!

**Comment by FBruzzesi** [comment]
Closing this in favor of #695 and what Anopsy already did

**Pull request closed without merging**
