### PR TITLE
release: bump version to 1.8.1

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [x] 🐳 Other

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
hey - it looks like this didn't quite work, no release was triggered https://pypi.org/project/narwhals/#history

which process did you follow?

**Comment by FBruzzesi** [comment]
> hey - it looks like this didn't quite work, no release was triggered https://pypi.org/project/narwhals/#history
> 
> which process did you follow?

Doesn't it need to be merged to trigger the release?

**Comment by MarcoGorelli** [comment]
the way it current works is that the `bump_version` script should add a tag, which is what triggers the release, I'm surprised that didn't happen

**Comment by FBruzzesi** [comment]
I will close this then

**Comment by MarcoGorelli** [comment]
it seems to have worked in https://github.com/narwhals-dev/narwhals/pull/979

no sure what happened - thanks anyway, we'll fix it later 🔧

**Pull request closed without merging**
