### PR TITLE
ci: enable uv cache, use astral-sh official action

### LINKED ISSUE #955: [Enh]: Use offical `astral-sh/setup-uv@v2` github action and enable caching in the CI
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

No response

### Please describe the purpose of the new feature or describe the problem to solve.

- We should use an official github action to install `uv` onto the running CI platform
- We can speed up the `uv install` CI step by caching the dependencies, since `requirements-dev.txt` does not change so often.

### Suggest a solution if possible.

```diff
...
        with:
          python-version: ${{ matrix.python-version }}
-     - name: Install uv (Unix)
-       if: runner.os != 'Windows'
-       run: curl -LsSf https://astral.sh/uv/install.sh | sh
-     - name: Install uv (Windows)
-       if: runner.os == 'Windows'
-       run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
+     - name: Install the latest version of uv
+       uses: astral-sh/setup-uv@v2
+       with:
+         version: "latest"
+     - name: Enable caching
+       id: setup-uv
+       uses: astral-sh/setup-uv@v2
+       with:
+         enable-cache: true
+         cache-suffix: "reqs-cache"
      - name: install-reqs
...
```

### If you have tried alternatives, please describe them below.

_No response_

### Additional information that may help us understand your needs.

_No response_

### PR DESCRIPTION
**Pull request by aidoskanapyanov**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #955

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

Also added `cache-dependency-glob` pattern to revalidate the cache whenever the `requirements-dev.txt` file is changed. I hope this will work, gotta test it :)

### CODE REVIEW

**Comment by aidoskanapyanov** [comment]
This is how `uv` cached the dependencies, I also added a `python-version` suffix to distinguish between versions:
https://github.com/narwhals-dev/narwhals/actions/caches

Shall we trigger CI rerun and see if it cuts the `install-reqs` step?

**Comment by MarcoGorelli** [comment]
did it work? shall we ship it?

**Comment by FBruzzesi** [comment]
> did it work? shall we ship it?

I honestly could not spot much of the difference, but still would prefer to use the _official_ action rather then a manual installation. 
From the [uv github section](https://docs.astral.sh/uv/guides/integration/github/), it seems we could use uv to install run tests as well (happy to keep it as a followup)

**Review by MarcoGorelli — APPROVED** [review]
agree - let's do this then, thanks @aidoskanapyanov !

**Comment by aidoskanapyanov** [comment]
image

I pulled up statistics for `pytest-38 (3.8, ubuntu-latest)` job in `PyTest` workflow for the last  60-ish days via `gh api`.
And it turns out there's really no difference in using cache for installing dependencies. If anything this may have slowed down the run times :/

**Comment by FBruzzesi** [comment]
I guess that uv is faster than building, checking and grabbing from a cache then 😂 Should we revert this one?

**Comment by aidoskanapyanov** [comment]
Yeah, I think we need to revert it, installing from `https://astral.sh/uv/install.sh` looked fine. Seems like a pretty permanent url 😂
Also, cache entries are piling up with each CI run in https://github.com/narwhals-dev/narwhals/actions/caches.
Some of them are being used, but I don't think it makes much of a different in performace.

**Comment by aidoskanapyanov** [comment]
> If anything this may have slowed down the run times 
Could also be that we've added 3 need dependencies since then

**Pull request merged**
