### PR TITLE
perf: Impove `pandas`-backend indexing

### LINKED ISSUE #992: [enh]: Pandas indexing is slow
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

_No response_

### Please describe the purpose of the new feature or describe the problem to solve.

As it currently stands the `pandas`-backend indexing operation is very slow in comparison to the native one, that is to say - the difference is `~6-9x` (depending on the run) worse for narwhals

```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3]})
df['a']
```

is much faster than

```python
import pandas as pd
import narwhals as nw
df = pd.DataFrame({'a': [1, 2, 3]})

nw_df = nw.from_native(df)
nw_df['a']
```

for reference am attaching the profiles of both indexing operations

native `pandas`
Screenshot 2024-09-18 at 13 18 01

narwhals `pandas`-backend
Screenshot 2024-09-18 at 13 16 13

as one can see native pandas does some caching, which is not the case in the narwhals case as the backend uses `loc` and `iloc` ubiquitously in the implementation of `__getitem__`, see this [here](https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_pandas_like/dataframe.py#L131-L199), which as evident are slow

Since the difference in `df[col]` and `df.loc[:, col]` are in assignment, and not assignemt is possible in `narwhals` in the form of `nw_df[col] = some_series`, this is a slowdown, which is unnecessary

Similar issues have `PandasLikeDataframe.select` and `PandasLikeDataFrame.with_columns`

### Suggest a solution if possible.

`__getitem__` needs to be reworked to use as much as possible the cache in the pandas dataframe object

### If you have tried alternatives, please describe them below.

_No response_

### Additional information that may help us understand your needs.

_No response_

### PR DESCRIPTION
**Pull request by aivanoved**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #992 

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
ooh nice one @aivanoved ! if we can get a perf improvement from this and it's safe, then it seems like a no-brainer

**Comment by aivanoved** [comment]
@MarcoGorelli It would be very nice! This is still in draft as am still checking that it is safe

**Comment by aivanoved** [comment]
I don't think there are any safety issues, at the same time thinking about how to test this has been slightly deadend-y. @MarcoGorelli any ideas for tests?

**Comment by MarcoGorelli** [comment]
I think this should be safe. We don't have any in-place operations in the API anyway - the only one is `Series.scatter`, and we really warn users to be careful with that one. And the scatter tests still pass here

**Comment by FBruzzesi** [comment]
Hey @aivanoved thanks for this improvement!
It seems that there are other pandas-like part of the codebase that use `loc[:, ...]`, should we migrate those as well before merging the changes?

**Comment by aivanoved** [comment]
@FBruzzesi I'll take a look at them again, as I was only looking at `__getitem__` specifically

If they are used in assignments, most likely they are meaningful

**Comment by aivanoved** [comment]
I have removed all which are not involved in assignments, also have left the dask backend untouched, as there I am not sure what the implications of the `loc` semantics

**Comment by MarcoGorelli** [comment]
thanks @aivanoved 

tbh i'm worried about trusting pandas here for anything more complicated than `df[column_name]`. for example:
```python
>>> df = pd.DataFrame({True: [1, 2], False: [3, 4]})
>>> df[[True,False]]
   True   False
0      1      3
```

For just taking out a single column into a Series (which is probably what we do most often), then it should be safe - shall we just stick to that for now?

**Review by MarcoGorelli — APPROVED** [review]
thanks a tonne @aivanoved for having spotted this and submitted a fix!

**Pull request merged**
