### PR TITLE
feat: add  `replace_strict`

### PR DESCRIPTION
**Pull request by MarcoGorelli**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Review by EdAbati — COMMENTED** [review]
Very nice! I added some questions and minor comments. I hope they are useful, if not feel free to ignore :)

**Comment by MarcoGorelli** [comment]
thanks @EdAbati for your review!

i've removed `replace` for now, we can address it later, `replace_strict` is more needed for the Plotly PR

I've also rewritten the signature to align it with the Polars args `old` and `new` instead of `mapping` - it's also a bit more concise to do 
```python
nw.col(col).replace_strict(order, range(len(order)))
```
than
```python
nw.col(col).replace_strict({key: i for i, key in enumerate(order)})
```

**Review by FBruzzesi — COMMENTED** [review]
Thanks @MarcoGorelli!

A couple of comments, the main concern being dask implementation. 
Big fan of letting go most of the `# pragma: no cover` 👌

**Review by EdAbati — COMMENTED** [review]
Thanks for the update, just added minor docs-related suggestions. :)

**Comment by MarcoGorelli** [comment]
Excellent comments, thanks both for reviews! 🙏 

i've amended the error message so now it shows something like:
```
ValueError: replace_strict did not replace all non-null values.

The following did not get replaced: ['cd']
```

**Comment by dangotbanned** [comment]
Just here following up on a blame that confused me

Have renamed the PR to reflect (https://github.com/narwhals-dev/narwhals/pull/1327#issuecomment-2462318319)

**Pull request merged**
