### PR TITLE
feat: Series.sum test case

### PR DESCRIPTION
**Pull request by mfonekpo**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [x] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [ ] Code follows style guide (ruff)
- [x] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
hey - you're missing quite a few parts, this should be very similar to https://github.com/narwhals-dev/narwhals/pull/457/files, please check that

**Comment by MarcoGorelli** [comment]
hi @mfonekpo - is it clear what you should do here?

**Comment by mfonekpo** [comment]
Yes Marco, I looked through the example you gave last night. I will
implement them today.

**Comment by MarcoGorelli** [comment]
thanks @mfonekpo for updating

could you take another look at https://github.com/narwhals-dev/narwhals/pull/457/files please? it should be identical to that PR, but with `sum` instead of `min` / `max`

**Review by MarcoGorelli — COMMENTED** [review]
Thanks @mfonekpo , this is really close

just one thing - as per https://github.com/narwhals-dev/narwhals/pull/515, `constructor_with_pyarrow` is now gone, you can just use `constructor`

could you please:
- `git fetch upstream`
- `git merge upstream/main`
- then, replace `constructor_with_pyarrow` with `constructor`
- check tests pass
- add, commit, push
- hopefully, it will all be green 🤞

**Review by MarcoGorelli — COMMENTED** [review]
thanks @mfonekpo 

looks like there's still a little more to do - there are some tests which are currently expected to fail, but thanks to your PR, they now pass 🥳 

```
___________________ test_sum_all[pyarrow_table_constructor] ____________________
[XPASS(strict)] 
_____________ test_renamed_taxicab_norm[pyarrow_table_constructor] _____________
[XPASS(strict)] 
```

To get CI green, could you please look for those two tests, and remove the
```python
    if "pyarrow_table" in str(constructor):
        request.applymarker(pytest.mark.xfail)
```
parts?

**Comment by MarcoGorelli** [comment]
almost there, just need to address
```
tests/expr/sum_all_test.py:7:18: ARG001 Unused function argument: `request`
  |
7 | def test_sum_all(request: Any, constructor: Any) -> None:
  |                  ^^^^^^^ ARG001
8 |     data = {"a": [1, 3, 2], "b": [4, 4, 6], "z": [7.0, 8, 9]}
9 |     df = nw.from_native(constructor(data), eager_only=True)
  |

tests/stable_api_test.py:11:31: ARG001 Unused function argument: `request`
   |
11 | def test_renamed_taxicab_norm(request: Any, constructor: Any) -> None:
   |                               ^^^^^^^ ARG001
12 |     # Suppose we need to rename `_l1_norm` to `_taxicab_norm`.
13 |     # We need `narwhals.stable.v1` to stay stable. So, we
   |
```
please make sure that `pre-commit run --all-files` passes - almost there!

**Review by FBruzzesi — APPROVED** [review]
Amazing work!

CuteCatFabulousGIF

**Pull request merged**
