### PR TITLE
feat: Added `Expr.abs` to Dask

### PR DESCRIPTION
**Pull request by mistShard**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #637 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.
I used `abs_test.py` to test the code. I'm not sure if the test is configured to test the method.

### CODE REVIEW

**Review by FBruzzesi — COMMENTED** [review]
Thanks for the PR 🚀

It just needs to remove the dask xfail in the dedicate `abs` test

**Comment by mistShard** [comment]
> Thanks for the PR 🚀
> 
> You just needs to remove the dask xfail in the dedicate `abs` test

done

**Comment by FBruzzesi** [comment]
> > Thanks for the PR 🚀
> > You just needs to remove the dask xfail in the dedicate `abs` test
> 
> done

there is an additional test that passes but marked as fail 🙃

**Review by MarcoGorelli — APPROVED** [review]
thanks @mistShard , and @FBruzzesi for reviewing

**Pull request merged**
