### PR TITLE
feat: add `Series|Expr` `cum_min` and `cum_max` methods

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues

- Related issue #1371 

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added
- [x] Documented the changes

### CODE REVIEW

**Comment by FBruzzesi** [comment]
Pyarrow introduced `cumulative_min`, `cumulative_max` and `cumulative_prod` in 13.0

**Comment by AlessandroMiola** [comment]
> Pyarrow introduced `cumulative_min`, `cumulative_max` and `cumulative_prod` in 13.0

Not sure if relevant, should we also re-map these into their polars native exprs via `POLARS_TO_ARROW_AGGREGATIONS` for use in `group_by` like exprs? Found this might be relevant on #1177.

**Comment by FBruzzesi** [comment]
> > Pyarrow introduced `cumulative_min`, `cumulative_max` and `cumulative_prod` in 13.0
> 
> Not sure if relevant, should we maybe also re-map these into their polars native exprs via `POLARS_TO_ARROW_AGGREGATIONS` for use in `group_by` like exprs? Found this might be relevant on #1177.

That's a very good point. However for arrow this is not possible, unless we move operations unsupported natively to use `__iter__`, but that would most likely be slow. [List of pyarrow grouped aggregations](https://arrow.apache.org/docs/14.0/python/compute.html#grouped-aggregations).

Regarding pandas, I will check that's possible to achieve

**Comment by AlessandroMiola** [comment]
> That's a very good point. However for arrow this is not possible, unless we move operations unsupported natively to use `__iter__`, but that would most likely be slow ([List of pyarrow grouped aggregations](https://arrow.apache.org/docs/14.0/python/compute.html#grouped-aggregations)).

ahhh, right, I see ✌️

**Review by MarcoGorelli — APPROVED** [review]
awesome, thanks @FBruzzesi !

**Pull request merged**
