### PR TITLE
feat: add dask `Expr.std`

### PR DESCRIPTION
**Pull request by anopsy**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #637 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.
Did not remove `if "dask"...` from std_test as its causes  `AttributeError: 'Scalar' object has no attribute 'name'`

### CODE REVIEW

**Comment by anopsy** [comment]
Yass! it works now - at least it passes the tests without AttributeError.

**Comment by MarcoGorelli** [comment]
nice one! the ci failure looks unrelated, one sec

**Comment by MarcoGorelli** [comment]
ok, done https://github.com/narwhals-dev/narwhals/pull/736

Sorry, one more fetch and merge upstream/main, then hopefully it'll be green 🥦

**Review by MarcoGorelli — APPROVED** [review]
thanks @anopsy !

**Pull request merged**
