### PR TITLE
ci: improve publish ci to use env vars

### LINKED ISSUE #1647: ci: use environment variables instead of contexts in `publish_to_pypi.yml`
We should apply the same diff from https://github.com/pypa/packaging.python.org/pull/1765/files to our [publish_to_pypi.yml](https://github.com/narwhals-dev/narwhals/blob/main/.github/workflows/publish_to_pypi.yml) file

### PR DESCRIPTION
**Pull request by Dhanunjaya-Elluri**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [x] 🐳 Other

## Related issues

- Related issue #1647 
- Closes #1647 

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below
This PR just improves the [publish_to_pypi.yml](https://github.com/narwhals-dev/narwhals/blob/main/.github/workflows/publish_to_pypi.yml) to use the environment variables.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks - think there's on emore change that needs doing from the linked pr?

**Comment by Dhanunjaya-Elluri** [comment]
@MarcoGorelli I guess not! Do you have any suggestions?

**Comment by MarcoGorelli** [comment]
I think there's the other change that still needs doing?

**Comment by Dhanunjaya-Elluri** [comment]
Hey @MarcoGorelli, I updated the PR. Just let me know if this what you meant. I might be missing some context😅

**Review by MarcoGorelli — APPROVED** [review]
thanks @Dhanunjaya-Elluri , let's see if this works

**Pull request merged**
