### PR TITLE
docs: add codespace steps and fork steps to `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by anopsy**
I added extra steps, I hope it's clear.
Once it's merged I'll add images to some steps. 
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @anopsy !

I like the codespaces part, and the enumeration!

I'm not 100% sure about adding too much details / images - perhaps we could instead advise people to first go through https://github.com/firstcontributions/first-contributions, and keep most of the contributing guide to more Narwhals-specific things?

Like this hopefully we can strike a balance between:
- making it accessible to newcomers
- keeping it not-too-long so that people who have contributed to other projects already can quickly find the information they need

?

**Review by MarcoGorelli — APPROVED** [review]
As in, what you've added here it great, I'm just not sure about making it much longer

nice one, feel free to merge when ready 🚀

**Comment by anopsy** [comment]
that's a fair point. Just to make sure, should I scrape some of the points and refer to first-contribution guide or can it stay as it is and I should just add reference to first-contributions?

**Comment by MarcoGorelli** [comment]
Just as a correction to my message above (which we discussed on Discord, I'm just posting it here so it's visible to others)

I think I was wrong in my earlier statement - it's better to err on the side of over-communicating, and we can just have a "tl;dr: if you're an experienced contributing, feel free to skip straight to steps 8-9" for experienced contributors

**Comment by anopsy** [comment]
Yes, I'll add that today in the evening. 🫡

**Pull request merged**
