### PR TITLE
doc: Fix link

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #https://github.com/narwhals-dev/narwhals/issues/476

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Review by FBruzzesi — APPROVED** [review]
Thanks! I opened the issue but was unsure about the link!

**Comment by DeaMariaLeon** [comment]
@FBruzzesi thanks for the approval. 🙂 The merging is blocked, should I just wait?

**Comment by FBruzzesi** [comment]
> The merging is blocked

Weird flex! In the protection rule I see only one approval is required. Did anything change recently? cc: @MarcoGorelli

**Comment by MarcoGorelli** [comment]
thanks for flagging - it should definitely be possible for one of you to approve and each others' PRs

**Comment by DeaMariaLeon** [comment]
@MarcoGorelli - it's working, thanks.

**Pull request merged**
