### PR TITLE
Implement n_unique

### PR DESCRIPTION
**Pull request by mistShard**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #372
- Closes #

## Checklist

- [ x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.
I implemented `n_unique`. A test file already existed, so I did not have to write a test

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks @mistShard !

It's true that a test file exists, but it does not yet test pyarrow

could you remove the lines
```
    if "pyarrow_table" in str(constructor):
        request.applymarker(pytest.mark.xfail)
```
from the test, and check that it still passes?

**Comment by mistShard** [comment]
When I deleted the lines you requested, the test threw the following error:

```
========================================================== test session starts ===========================================================
platform win32 -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: C:\Users\hp\Documents\Work\OpenTeams\narwhals
configfile: pyproject.toml
plugins: hypothesis-6.103.2, cov-5.0.0
collected 5 items

tests\expr_and_series\n_unique_test.py ....F                                                                                        [100%]

================================================================ FAILURES ================================================================ 
________________________________________________ test_n_unique[pyarrow_table_constructor] ________________________________________________ 

request = <FixtureRequest for <Function test_n_unique[pyarrow_table_constructor]>>
constructor = <function pyarrow_table_constructor at 0x000002089171E7A0>

    def test_n_unique(request: Any, constructor: Any) -> None:

        df = nw.from_native(constructor(data), eager_only=True)
        result = df.select(nw.all().n_unique())
        expected = {
            "a": [3],
            "b": [4],
        }
>       compare_dicts(result, expected)

tests\expr_and_series\n_unique_test.py:22:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

result = ┌───────────────────────────────────────────────┐
| Narwhals DataFrame                            |
| Use `narwhals.to_native` to see native output |
└───────────────────────────────────────────────┘
expected = {'a': [3], 'b': [4]}

    def compare_dicts(result: Any, expected: dict[str, Any]) -> None:
        if hasattr(result, "collect"):
            result = result.collect()
        if hasattr(result, "columns"):
            for key in result.columns:
                assert key in expected
        for key in expected:
            for lhs, rhs in zip_strict(result[key], expected[key]):
                if hasattr(lhs, "as_py"):
                    lhs = lhs.as_py()  # noqa: PLW2901
                if hasattr(rhs, "as_py"):  # pragma: no cover
                    rhs = rhs.as_py()  # noqa: PLW2901
                if isinstance(lhs, float) and not math.isnan(lhs):
                    assert math.isclose(lhs, rhs, rel_tol=0, abs_tol=1e-6), (lhs, rhs)
                elif isinstance(lhs, float) and math.isnan(lhs):
                    assert math.isnan(rhs), (lhs, rhs)  # pragma: no cover
                elif pd.isna(lhs):
                    assert pd.isna(rhs), (lhs, rhs)
                else:
>                   assert lhs == rhs, (lhs, rhs)
E                   AssertionError: (2, 3)

tests\utils.py:39: AssertionError
======================================================== short test summary info =========================================================
FAILED tests/expr_and_series/n_unique_test.py::test_n_unique[pyarrow_table_constructor] - AssertionError: (2, 3)
====================================================== 1 failed, 4 passed in 1.61s ======================================================= 
```

**Comment by MarcoGorelli** [comment]
thanks @mistShard ! that's a clue that something needs changing in the implementation 😉

**Comment by mistShard** [comment]
@MarcoGorelli I'll resolve it. A preliminary examination suggests that it has to do with `None`s not being counted by PyArrow's `.count()`

**Comment by MarcoGorelli** [comment]
that's a good observation! does it work to just use `len`?

**Comment by mistShard** [comment]
@MarcoGorelli Thanks for the feedback. I found that `pyarrow.compute` does not have a `len` nmethod (_maybe I just didn't see it and it was staring me in the face_). Instead I used the `mode="all"` parameter to make the `.count()` method operate on all unique values null or otherwise.

`n_unique` passed the test after I made the alterations I did.

**Comment by MarcoGorelli** [comment]
woooow! well done @mistShard !

I think the mypy issue is unrelated, will, but this should be it! nice one!

**Comment by MarcoGorelli** [comment]
ah yeah, there's been a new mypy release

if you mark as ready for review, we can ship this one!

**Comment by mistShard** [comment]
@MarcoGorelli marked for review

**Review by FBruzzesi — APPROVED** [review]
It looks good to me 👌 so I will start with the kitty gifs 😂

MeowKittyGIF

**Comment by MarcoGorelli** [comment]
😄 let's ship it - seriously great job here @mistShard , it's hard to believe that just a few weeks ago you weren't familiar with pandas and now you've figured this all out by yourself

**Pull request merged**
