### PR TITLE
fix: fixing unnesscary raise of mean_horizontal

### LINKED ISSUE #1081: bug: `nw.mean_horizontal(nw.all())` raises unnecessarily
Follow-up to https://github.com/narwhals-dev/narwhals/pull/1075

### PR DESCRIPTION
**Pull request by Cheukting**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [X] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #1081 
- Closes #1081 

## Checklist

- [X] Code follows style guide (ruff)
- [X] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

See #1081

### CODE REVIEW

**Comment by Cheukting** [comment]
mean_horizontal was implemented in Polars 0.20.8: https://github.com/pola-rs/polars/releases/tag/py-0.20.8

**Review by FBruzzesi — COMMENTED** [review]
Hey @Cheukting thanks for addressing this!

Probably it's an obsession of mine, but can we keep using generator comprehensions instead of list and for loops?

Regarding polars, we already have the `if version` check, so such branch will need the same adjusting as other backend I imagine

**Comment by Cheukting** [comment]
All checks have passed @MarcoGorelli ship it! (What cute animal do we have time?)

@FBruzzesi are you sure you want me to refactor them? Because in the for loop there is already a list comprehension, it will become a list comprehension within a list comprehension...  it will not be very readable (IMHO)... here is a preview example:
```
            series = [
                series.extend([_series.fill_null(0) for _series in _expr._call(df)]) for _expr in parsed_exprs
            ]
```

I can refactor with no problem if it is preferred. Just wanna double check.

**Comment by FBruzzesi** [comment]
Hey hey @Cheukting 

> All checks have passed @MarcoGorelli ship it! (What cute animal do we have time?)

Awesome! I will let Marco pick animal(s) 😂 

> are you sure you want me to refactor them? Because in the for loop there is already a list comprehension, it will become a list comprehension within a list comprehension... it will not be very readable (IMHO)

I did the same in #1090, e.g. generator like the following:
```py
series = (s for _expr in parsed_exprs for s in _expr._call(df))
```

Actually I think this PR should take #1090 into account and set 
```py
output_names=reduce_output_names(parsed_exprs),
```
in `mean_horizontal` as well, otherwise we can end up in a similar issue to what's addressed there

**Review by MarcoGorelli — APPROVED** [review]
Thanks @Cheukting , and thanks @FBruzzesi for reviewing!

love this

**Pull request merged**
