### PR TITLE
feat: add `DataFrame|LazyFrame.cast` method

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [x] Documented the changes

## If you have comments or can explain your changes, please do so below.

Additionally extends `Expr|Series.cast` with `strict` argument

### CODE REVIEW

**Comment by FBruzzesi** [comment]
Unrelated CI failure

**Comment by MarcoGorelli** [comment]
thanks @FBruzzesi !

are we sure we need this? I think this can currently be accomplished with `with_columns` and `Expr.cast`, no? e.g.
```
df.with_columns(nw.all().cast(nw.String))
```
or
```
df.with_columns(nw.col(col).cast(dtype) for col, dtype in dtypes.items())
```
?

i'm just a little unsure about expanding the `DataFrame` / `LazyFrame` API when there's a simple `Expr` solution

**Comment by FBruzzesi** [comment]
> i'm just a little unsure about expanding the DataFrame / LazyFrame API when there's a simple Expr solution

Fair enough!

Polars exposed it, it isa nice shortcut I am reaching out for, but definitly there is an Expr workaround

**Comment by FBruzzesi** [comment]
Closing as not planned for now

**Comment by MarcoGorelli** [comment]
sure, thanks - we can always reconsider later

**Comment by FBruzzesi** [comment]
Yep, agree! This PR has so many conflicts that even if we want to consider adding it, it would be just easier to write it from scratch.

I am trying to do some cleanup, especially before sprints 😁

**Pull request closed without merging**
