### PR TITLE
Simplify return function in `_pandas_like.utils.py`

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [x] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.
Per comment: on https://github.com/narwhals-dev/narwhals/pull/1192#discussion_r1802948783

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks - can we go further and combine them more? like
```python
    if dtype.startswith(("large_list", "list", "fixed_size_list", "struct")):
        return arrow_native_to_narwhals_dtype(native_column.dtype.pyarrow_dtype, dtypes)
```

**Comment by DeaMariaLeon** [comment]
>can we go further and combine them more? 

Should have thought about it..

**Comment by DeaMariaLeon** [comment]
I'm looking at https://github.com/marimo-team/marimo/blob/main/marimo/_plugins/ui/_impl/tables/narwhals_table.py#L97

**Review by MarcoGorelli — APPROVED** [review]
thanks @DeaMariaLeon ! the ci failure seems unrelated - i'll take a look, but we can merge this in the meantime

**Pull request merged**
