### PR TITLE
feat: dask in api-completeness table

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

Adds dask in api-completeness doc page: I think it will be a easy entrypoint to easily see what's still missing from the API.

~In terms of script and final output, I will try to spend some time and give it some more love in the near future 😇~

Ok so it was quicker and simpler than excepted. The new script generate 3 files (dataframe.md, expr.md and series.md) into the api-completeness folder dynamically. There are still some improvements to be made (e.g. lazy vs eager)

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
nice 🙏 ! we're not currently mentioning Dask at all in the docs, perhaps let's get a little further before merging this?

**Comment by FBruzzesi** [comment]
> nice 🙏 ! we're not currently mentioning Dask at all in the docs, perhaps let's get a little further before merging this?

Sure, let's do that! This will have no conflicts with the main codebase anyway :)

**Comment by MarcoGorelli** [comment]
we're probably far enough with Dask that we can merge this?

**Review by MarcoGorelli — APPROVED** [review]
approving then, feel free to merge if you agree

**Pull request merged**
