### PR TITLE
feat: add `Series|Expr.cum_count` method

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues

- Related issue #1371

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added
- [x] Documented the changes

## If you have comments or can explain your changes, please do so below

I have dask skill issues. Replicating what works for pandas raises an error:

>     def _divisions(self):
>        # This is an issue.  In normal Dask we re-divide everything in a step
>        # which combines divisions and graph.
>        # We either have to create a new Align layer (ok) or combine divisions
>        # and graph into a single operation.
>        dependencies = self.dependencies()
>        for arg in dependencies:
>            if not self._broadcast_dep(arg):
>               assert arg.divisions == dependencies[0].divisions
> E               AssertionError

Code:

```py
def cum_count(self, reverse):
    def func(_input: dask_expr.Series, _reverse: bool) -> dask_expr.Series:
        not_na_series = (~_input.isna()).astype(int)
        return (
            not_na_series.cumsum()
            if not _reverse
            else _input.size - not_na_series.cumsum() + not_na_series - 1
       )

return self._from_call(
    func,
    "cum_count",
    reverse,
    returns_scalar=False,
)
```

### CODE REVIEW

**Comment by FBruzzesi** [comment]
Betrayed by old polars version itself

**Comment by MarcoGorelli** [comment]
yeah it switched from starting at 0 to starting at 1 at some point...tbh i think it should've been a minor version change rather than a patch one

**Review by MarcoGorelli — APPROVED** [review]
wonderful, thanks @FBruzzesi !

agree on keeping Dask out of this for now, as we need to exclude row-order-dependent operations for lazy-only backends

**Comment by FBruzzesi** [comment]
> yeah it switched from starting at 0 to starting at 1 at some point...tbh i think it should've been a minor version change rather than a patch one

Should we check and branch out for other minor polars versions for this?

**Comment by FBruzzesi** [comment]
> agree on keeping Dask out of this for now, as we need to exclude row-order-dependent operations for lazy-only backends

Happy you agree! My issue was `reverse=True` was failing with the error in the description

**Comment by FBruzzesi** [comment]
> > Should we check and branch out for other minor polars versions for this?
> 
> not sure i understand the question / issue, sorry, it looks like your PR already handles the different Polars versions perfectly?

So in polars==0.20.3, `cum_count` does not exist, hence my "workaround" implementation.
However you mentioned that possibly when introduced the count was starting from 0. Since we don't have tests for _every single version_, I am not sure we cover such case.

**Comment by MarcoGorelli** [comment]
ah it changed in 0.20.4, so you already covered it 🙌

**Pull request merged**
