### PR TITLE
feat: Implement `head` and `tail` for PandasLike DataFrames

### PR DESCRIPTION
**Pull request by condekind**
This PR introduces head and tail for PandasLike DataFrames.

I have a question: I'd like to add tests - should I construct a pandas* df in a test without using `constructor`, since the feature being added is not yet supported by other back ends?

*the same question goes to other back-ends when they're the first (or rather, not the last) to get a feature

## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by lucianosrp** [comment]
> I have a question: I'd like to add tests - should I construct a pandas* df in a test without using constructor, since the feature being added is not yet supported by other back ends?
>
>*the same question goes to other back-ends when they're the first (or rather, not the last) to get a feature


Hey @condekind! 
You can add the `constructor` and `request` fixture to a test to "catch" the backends that are not yet implemented.

See example below:
```python
def test_from_dict(constructor: Any, request: Any) -> None:
    if "dask" in str(constructor):
        request.applymarker(pytest.mark.xfail)
    df = nw.from_native(constructor({"a": [1, 2, 3], "b": [4, 5, 6]}))
    native_namespace = nw.get_native_namespace(df)
    result = nw.from_dict({"c": [1, 2], "d": [5, 6]}, native_namespace=native_namespace)
    expected = {"c": [1, 2], "d": [5, 6]}
    compare_dicts(result, expected)
    assert isinstance(result, nw.DataFrame)
```
In your case, I'd add something like: 
```python
if "pandas" not in str(constructor): 
    request.applymarker(pytest.mark.xfail)
```

I hope this helps! 😄

**Comment by condekind** [comment]
> > I have a question: I'd like to add tests - should I construct a pandas* df in a test without using constructor, since the feature being added is not yet supported by other back ends?
> > *the same question goes to other back-ends when they're the first (or rather, not the last) to get a feature
> 
> Hey @condekind! You can add the `constructor` and `request` fixture to a test to "catch" the backends that are not yet implemented.
> 
> See example below:
> 
> ```python
> def test_from_dict(constructor: Any, request: Any) -> None:
>     if "dask" in str(constructor):
>         request.applymarker(pytest.mark.xfail)
>     df = nw.from_native(constructor({"a": [1, 2, 3], "b": [4, 5, 6]}))
>     native_namespace = nw.get_native_namespace(df)
>     result = nw.from_dict({"c": [1, 2], "d": [5, 6]}, native_namespace=native_namespace)
>     expected = {"c": [1, 2], "d": [5, 6]}
>     compare_dicts(result, expected)
>     assert isinstance(result, nw.DataFrame)
> ```
> 
> In your case, I'd add something like:
> 
> ```python
> if "pandas" not in str(constructor): 
>     request.applymarker(pytest.mark.xfail)
> ```
> 
> This way, you can write one test for all backends. Pytest will just mark everything that goes in that "if clause" with `xfail`
> 
> As more backends get implemented, the if condition can be modified and eventually completely removed when all backends of `constructor` are supported.
> 
> I hope this helps! 😄

This helps a lot!! Thank you :)

**Comment by condekind** [comment]
Strange, it seems head and tail already exist, I don't know why they're marked with an X in the api-completeness page. I'm closing this, and I'll look for something else that's not yet implemented. I appreciate the suggestion, though!

**Comment by condekind** [comment]
I misread the table in the api-completeness page.
head and tail are not impl. for SeriesStringNamespace, not DataFrame.
I'll leave this closed

**Pull request closed without merging**
