### PR TITLE
docs: Avoid copying >>> and ... from clipboard

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes # https://github.com/narwhals-dev/narwhals/issues/1338

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

## If you have comments or an explain your changes, please do so below.
Copied from https://github.com/astral-sh/ruff/blob/main/docs/js/extra.js

### CODE REVIEW

**Review by FBruzzesi — APPROVED** [review]
This is just magical to me 😂 
Thanks a ton @DeaMariaLeon ! I took the liberty to add a couple of lines to better point at the original source of the file and team who created it!

HighFiveCatFiveGIF

**Comment by DeaMariaLeon** [comment]
Thank you @FBruzzesi for adding the source information. Much better.

**Comment by lorentzenchr** [comment]
Have you tested it?
If I copy (copy to clipboard button) the first example of https://narwhals-dev.github.io/narwhals/api-reference/dataframe/, I get:

```
>>> import pandas as pd
>>> import polars as pl
>>> import pyarrow as pa
>>> import narwhals as nw
>>> from narwhals.typing import IntoFrame
>>>
>>> df = {"foo": [1, 2, 3], "bar": [6.0, 7.0, 8.0], "ham": ["a", "b", "c"]}
>>> df_pd = pd.DataFrame(df)
>>> df_pl = pl.DataFrame(df)
>>> df_pa = pa.table(df)
```

**Comment by DeaMariaLeon** [comment]
Yes I did, it was working when I tested it. Need to investigate then.

**Comment by MarcoGorelli** [comment]
looks like there's two `extra_javascript` keys, they probably just need combining

**Comment by MarcoGorelli** [comment]
addressed - thanks @lorentzenchr for reporting!

**Pull request merged**
