### PR TITLE
feat: add `Series` and `Expr` `arg_min` & `arg_max`

### LINKED ISSUE #1492: feat: Series.arg_min, Series.arg_max, Expr.arg_min, Expr.arg_max
These would all be useful in Prophet, I think we should add them

### PR DESCRIPTION
**Pull request by Nathan-Bransby-NMT**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [x] ✅ Test
- [ ] 🐳 Other

## Related issues

- Related issue #1492
- Closes #1492 

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added
- [ ] Documented the changes

### Documentation Updates:
* [`docs/api-reference/expr.md`](diffhunk://#diff-e69825f3917ed6bbcde7210918515e093c0583688a5e4a575e078c6ee015d964R11-R12): Added `arg_min` and `arg_max` to the list of functions.
* [`docs/api-reference/series.md`](diffhunk://#diff-5f45d42af45324bacb9364605e79f506699e0fbd901d25e1ede6e0a56a24f7c2R14-R15): Added `arg_min` and `arg_max` to the list of functions.

### Implementation of `arg_min` and `arg_max`:
* [`narwhals/_arrow/expr.py`](diffhunk://#diff-a2caa9f0d49838e83344364b32ff5012fbaa69a71257ff702b11229958d576b3R270-R275): Added `arg_min` and `arg_max` methods.
* [`narwhals/_arrow/series.py`](diffhunk://#diff-f595265984b673e1c612607ebc3426434ee7162684840b99cd73fcce59fd6a7fR290-R301): Added `arg_min` and `arg_max` methods with `pyarrow.compute` implementation.
* [`narwhals/_pandas_like/expr.py`](diffhunk://#diff-0ded7e876f1f6f0aa79abda7252f76be22c1a01b1e97e7b65a5da8fa23e35ffdR263-R268): Added `arg_min` and `arg_max` methods.
* [`narwhals/_pandas_like/series.py`](diffhunk://#diff-59107550a5dea2a4834f7beb8d822b53e59f7abc7f24727dc48cd6d97c076c93R285-R292): Added `arg_min` and `arg_max` methods using native series.
* [`narwhals/_polars/expr.py`](diffhunk://#diff-1cb770b4b6397dfc5ad5fa5d9c517baf626b44557c6d9b7db6648b14a46c6101R168-R174): Added `arg_min` and `arg_max` methods.
* [`narwhals/_polars/series.py`](diffhunk://#diff-bedbce3a4c31ce874af737753bb15fa2463628fa752652a399e8dd5b07af73b1R223-R228): Added `arg_min` and `arg_max` methods using native series.
* [`narwhals/expr.py`](diffhunk://#diff-8dbec323eb770e099734f31eb6dd160668841972f5549ea2d00779ea65853ec5R965-R1064): Added `arg_min` and `arg_max` methods with comprehensive examples for various dataframes.
* [`narwhals/series.py`](diffhunk://#diff-a05a3e6be8017e9767b6ee214af34fb2425fd0e038e3881165c4a27fe180004dR841-R895): Added `arg_min` and `arg_max` methods with examples for different series.

## If you have comments or can explain your changes, please do so below

> This pull request introduces the `arg_min` and `arg_max` functions across various modules and documentation. These functions return the index of the minimum or maximum value in a series or expression. The most important changes include updates to the documentation, implementation of these functions in different files, and examples demonstrating their usage.

### CODE REVIEW

**Comment by Nathan-Bransby-NMT** [comment]
@devdanzin I'm sorry, I'm not at home. 

I shouldn't have tried to merge from the mobile app 🤦‍♂️ Are you able to check out what happened? 

If not I will have a look when I get home.

**Review by FBruzzesi — COMMENTED** [review]
Thanks @Nathan-Bransby-NMT! The changes look great already!

I have left a couple of comments which should be quick to fix. The remaining step is to add tests in `./tests/expr_and_series/` folder

**Comment by devdanzin** [comment]
> I shouldn't have tried to merge from the mobile app 🤦‍♂️ Are you able to check out what happened?

Thanks for merging!

I don't see any issues with the merge of my PR, do you mean merging the other PR? I think it'll be OK, we (or the maintainers) can squash the commits.

I'll add the requested changes to the open PR in your fork.

**Comment by MarcoGorelli** [comment]
thanks al! we squash and merge PRs so no need to worry about about the individual commits

**Comment by devdanzin** [comment]
Thanks for the review and guidance!

I'm sending PRs to @Nathan-Bransby-NMT's fork so we can work together, you can take a look at https://github.com/Nathan-Bransby-NMT/narwhals/pull/3 if you want to preview the changes (currently addressing review comments and adding tests).

**Review by MarcoGorelli — COMMENTED** [review]
I'm impressed - this is close!

There's some pre-commit failures that need addressing: https://results.pre-commit.ci/run/github/760058710/1733569567.tano9WQkSby1R68KlmbIng

If you run `pre-commit run --all-files` you'll need to get that to pass

**Comment by Nathan-Bransby-NMT** [comment]
@MarcoGorelli Sorry I just got home, I'll work on this now

**Comment by FBruzzesi** [comment]
Hey @Nathan-Bransby-NMT @devdanzin I think this is extremely close to being approved and merge. I have a tiny request on the test side: I think it would be nice to make a custom index for pandas, so that we verify that it's not the index being picked up.

I would suggest to change the index via `nw.maybe_set_index`, e.g.:

```py
df = nw.maybe_set_index(nw.from_native(data), column_names=["a"]
```
and then exclude column `"a"` when performing `arg_max/min`

**Comment by devdanzin** [comment]
Thank you for the review and suggestion!

> I think it would be nice to make a custom index for pandas
> [...]
> I would suggest to change the index via `nw.maybe_set_index`, e.g.:
> [...]
> and then exclude column `"a"` when performing `arg_max/min`

I'm not sure about the best way of making a custom index for pandas only, does this make sense? Is this in the right ballpark of what you're asking for?

```python
def test_expr_arg_max_expr(constructor_eager: ConstructorEager) -> None:
    native = constructor_eager(data)
    if native.__class__ == PandasDataFrame:
        df = nw.maybe_set_index(nw.from_native(native), column_names=["a"])
    else:
        df = nw.from_native(native)
    result = df.select(nw.col("b", "z").arg_max())
    expected = {"b": [2], "z": [2]}
    assert_equal_data(result, expected)
```

**Comment by MarcoGorelli** [comment]
i think just
```
df = nw.maybe_set_index(nw.from_native(native), column_names=["a"])
```
in all cases probably works

**Comment by MarcoGorelli** [comment]
i think you could do it for series too, e.g.
```
s = nw.maybe_set_index(s, index=[1,2,3])
```

**Review by MarcoGorelli — APPROVED** [review]
thanks all

**Pull request merged**
