### PR TITLE
feat: add `<min|max>_horizontal`

### LINKED ISSUE #1147: [Enh]: adding the method min_horizontal
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

_No response_

### Please describe the purpose of the new feature or describe the problem to solve.

In an implementation I'm working on using Narwhal, having a method like min_horizontal, as in Polars, would be very useful.

### Suggest a solution if possible.

_No response_

### If you have tried alternatives, please describe them below.

_No response_

### Additional information that may help us understand your needs.

_No response_

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Closes #1147

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [x] Documented the changes

### CODE REVIEW

**Comment by FBruzzesi** [comment]
Nightly failure unrelated:

> Collecting pandas
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.anaconda.org', port=443): Read timed out. (read timeout=15)")': /scientific-python-nightly-wheels/simple/pandas/3.0.0.dev0%2B1560.g5829e3ea20/pandas-3.0.0.dev0%2B1560.g5829e3ea20-cp311-cp311-manylinux_2_17_x86_64.manylinux20[14](https://github.com/narwhals-dev/narwhals/actions/runs/11212395241/job/31163532822?pr=1148#step:8:15)_x86_64.whl

**Comment by MarcoGorelli** [comment]
nice, thanks!

regarding concatenating and using `axis=1` - reckon we should do that for `sum_horizontal` / `mean_horizontal` too?

**Review by MarcoGorelli — APPROVED** [review]

**Comment by FBruzzesi** [comment]
> regarding concatenating and using `axis=1` - reckon we should do that for `sum_horizontal` / `mean_horizontal` too?

It may be worth checking performances also in terms of memory?

**Comment by MarcoGorelli** [comment]
yup! memray is pretty good for that

**Pull request merged**
