### PR TITLE
chore: extend `Implementation` for all backends

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [x] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [x] Documented the changes

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
nice, thanks @FBruzzesi !

**Comment by FBruzzesi** [comment]
>  just a mypy issue

How dare?!

**Comment by MarcoGorelli** [comment]
really nice, thanks @FBruzzesi !

Maybe the signature is fine with `native_namespace` rather than `Implementation`? Because then, for anyone extending Narwhals, we give them a possibility of including `.from_dict` in their native namespace, whereas if they need to pass `Implementation`, then it's not clear how they can modify one of our enums

**Comment by FBruzzesi** [comment]
> Maybe the signature is fine with `native_namespace` rather than `Implementation`? 

We may add it in the signature and one of the two has to be not None. 

> Because then, for anyone extending Narwhals, we give them a possibility of including `.from_dict` in their native namespace, whereas if they need to pass `Implementation`, then it's not clear how they can modify one of our enums

It would break in any case right? As it would branch to the block:

```py
 else:  # pragma: no cover
        msg = f"Expected library supported by Narwhals, got: {native_namespace}"
        raise ValueError(msg)
```

**Comment by MarcoGorelli** [comment]
> It would break in any case right? As it would branch to the block:

true, but we could just do a blanket
```
else:
    native_namespace.from_dict(data
```
and note in the "extending.md" docs that the native namespace is expected to implement `from_dict`

**Comment by FBruzzesi** [comment]
I like that :)

**Comment by FBruzzesi** [comment]
Taking a look at this. We would need to expose an `implementation` attribute/property in Narhwals BaseFrame as well. Any concern?

**Comment by MarcoGorelli** [comment]
i'm not sure I see why, but i'm probably missing something, if you open draft pr with what you have i'll take a look

**Pull request merged**
