### PR TITLE
docs: Pyarrow example docstrings for `Expr` and stable v1 API

### PR DESCRIPTION
**Pull request by CarloLepelaars**
## What type of PR is this? (check all applicable)

- [x] 📝 Documentation

## Related issues 

- Related issue #1000 

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [x] Documented the changes

## If you have comments or can explain your changes, please do so below.

PyArrow docstring examples for `narwhals/expr.py` and `narwhals/stable/v1/__init__.py`. 

I know #1000 mentions to do 4 functions in 1 PR, but was in a good flow so did the full `expr.py`. 😊  I think it's still within reason for review.

### CODE REVIEW

**Review by EdAbati — COMMENTED** [review]
Thank you for the effort! :)

It all looks great to me, I just suggested to add a couple of comments for consistency with polars.

Tests being green makes confindent to approve, but because of the size of the PR, I'd wait a bit for another review before merging (I may have missed something)

**Review by EdAbati — APPROVED** [review]
Nice! Thanks again 👌

**Review by FBruzzesi — APPROVED** [review]
Wow crazy effort! Thanks a ton for this one! I skimmed through it without noticing anything wrong, and also trust the doctests 😂

**Review by MarcoGorelli — APPROVED** [review]
thanks @CarloLepelaars , and thanks @EdAbati for reviewing!

**Pull request merged**
