### PR TITLE
feat: dask `columns` property & `filter` method

### PR DESCRIPTION
**Pull request by benrutter**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #637

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

This is a pretty small PR! I mainly wanted to get a feel for the API 😁 (initially made lots of changes as if it was a regular DataFrame and then remembered it was lazy!)

Adds in a `columns` property for the DaskLazyFrame.

EDIT: Ok, I couldn't resist tinkering. This now applies a fair bit more functionality, getting 'filter' to work (at least for some basic cases since the expressions still aren't fully complete).

I've added in "not-implemented" functions (i.e. empty functions that just raise an error) to appease mypy type checking. I figured this was a better move that `# type: ignore` annotation since they actually will be needed at some point, but let me know if the other approach would be better!

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
legend, mate!

**Comment by benrutter** [comment]
Ah yikes! Sorry @MarcoGorelli but just a heads up that I (*annoyingly*) pushed changes at the exact same time as your approval!

(don't merge without rechecking since you'll get a lot more than you signed up for!)

**Comment by MarcoGorelli** [comment]
😄 thanks Ben! Happy to take the extra stuff too, we just need test coverage for them

**Comment by benrutter** [comment]
Working on it! Any guidance on stuff like the `__lt__` implementation testing? (I'm good to add testing for them alonside the `all_horizontal` and `_create_expr_from_callable` methods but wasn't sure if it's needed since they just call out the dask's own codebase)

**Comment by MarcoGorelli** [comment]
i think just having some comparisons test in which gt/lt/le/ge are all tests together would be good
true that it's identical, but still

maybe we can soon add dask to the constructor fixture anyway, then we can just reuse existing tests

**Comment by benrutter** [comment]
(ok, adding in proper testing has shown me it's actually a little more complex than I'd thought - filter etc is working for simple cases like `col('a') > 43` but something odd is happening when I'm cross comparing `col('a') > col('b')`.

I'll revert the last commit and put it in a bit later as a seperate PR!

**Review by FBruzzesi — COMMENTED** [review]
This is awesome! I was planning a similar PR as a follow up from #667 !
I think `__and__` implementation is missing to make `all_horizontal` work with multiple statements 😇 but we can keep it as a follow up as well 🔥

**Review by MarcoGorelli — APPROVED** [review]

**Pull request merged**
