### PR TITLE
fix: `drop_nulls` with subset of length>1

### LINKED ISSUE #1088: [Bug]: Run into safety assertion on `reuse_series_implementation` for drop_nulls
### Describe the bug

When executing `DataFrame.drop_nulls(subset=[...])` we run into safety assertion of `reuse_series_implementation` function

### Steps or code to reproduce the bug

Consider the following tests:

```py
@pytest.mark.parametrize(
    ("subset", "expected"),
    [
        ("a", {"a": [1, 2.0, 4.0], "b": [float("nan"), 3.0, 5.0]}),
        (["a"], {"a": [1, 2.0, 4.0], "b": [float("nan"), 3.0, 5.0]}),
        (["a", "b"], {"a": [2.0, 4.0], "b": [3.0, 5.0]})
    ]
)
def test_drop_nulls_subset(constructor: Constructor, subset: str | list[str], expected: dict[str, float]) -> None:
    result = nw.from_native(constructor(data)).drop_nulls(subset=subset)
    compare_dicts(result, expected)
```

It will raise for arrow and pandas-like engines, not for polars or dask when subset has more than one column

### Expected results

To not raise

### Actual results

Raise AssertionError

### Please run narwhals.show_version() and enter the output below.

```shell
Latest narwhals
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Closes #1088

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [ ] Documented the changes

## If you have comments or can explain your changes, please do so below.

This might not be the permanent fix to the issue, consider it as a hotfix for now

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
thanks for spotting this

i think the issue is just that `any_horizontal` should always only just return a single column, so we could do
```diff
             root_names=combine_root_names(parsed_exprs),
-            output_names=parsed_exprs[0]._output_names,
+            output_names=parsed_exprs[0]._output_names[:1],
         )
 
     def any_horizontal(self, *exprs: IntoPandasLikeExpr) -> PandasLikeExpr:
@@ -262,7 +262,7 @@ class PandasLikeNamespace:
             depth=max(x._depth for x in parsed_exprs) + 1,
             function_name="any_horizontal",
             root_names=combine_root_names(parsed_exprs),
-            output_names=parsed_exprs[0]._output_names,
+            output_names=parsed_exprs[0]._output_names[:1],
         )
```
and that should fix it without needing to do other changes

**Comment by FBruzzesi** [comment]
`parsed_exprs[0]._output_names` can easily be None though.

Do you like: 
```diff
- output_names=parsed_exprs[0]._output_names,
+ output_names=(parsed_exprs[0]._output_names or [None])[:1],
```

**Comment by MarcoGorelli** [comment]
are you're right - let's make a function then, just like we have for `combine_root_names` one line above? in there we can explain that we follow the right-hand-rule like Polars does

**Comment by FBruzzesi** [comment]
> right-hand-rule like Polars does

left-most?

>  let's make a function then

Not sure I follow 100%. `combine_root_names` seems generic-ish.

For this (horizontal) reduction I would expect to have:

- left-most output name if available
- otherwise? left most root name?

**Comment by MarcoGorelli** [comment]
yup, left-most, sorry :)

so `parsed_exprs[0]._output_names[:1] if parsed_exprs[0]._output_names is not None else None`

**Review by MarcoGorelli — APPROVED** [review]
love this

thanks @FBruzzesi !

**Pull request merged**
