### PR TITLE
feat: Add `Expr.round` to Dask

### PR DESCRIPTION
**Pull request by mistShard**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #637 
- Closes #

## Checklist

- [x] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Review by FBruzzesi — COMMENTED** [review]
Thanks for the PR. Tests are passing but marked as xfail!
After fixing that we can merge! 🙌🏼

**Comment by DeaMariaLeon** [comment]
Don't we have to add tests??

**Comment by MarcoGorelli** [comment]
yup, @mistShard could you try removing the xfails from the round test for dask?

**Comment by MarcoGorelli** [comment]
could you try removing the xfails from the round test for dask?

**Comment by mistShard** [comment]
@MarcoGorelli I have done that and the tests do not run. I instead get this error:
```
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "C:\Users\hp\Documents\Work\OpenTeams\narwhals\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1487, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "C:\Users\hp\Documents\Work\OpenTeams\narwhals\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1539, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: env

========================================================== no tests ran in 0.19s 
```
Do I need to update pytest?

**Comment by mistShard** [comment]
other tests also show the same error

**Comment by MarcoGorelli** [comment]
You need to update your environment, run 

pip install -r requirements-dev.txt

**Comment by mistShard** [comment]
bit of a dumb question here. As a rule, how do I know by myself that my environment needs to be updated?

**Comment by mistShard** [comment]
@MarcoGorelli tests pass

**Review by MarcoGorelli — APPROVED** [review]
should be good, thanks @mistShard !

**Pull request merged**
