### PR TITLE
docs: fix `typing` link

### PR DESCRIPTION
**Pull request by FBruzzesi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## If you have comments or can explain your changes, please do so below.

Link referring wrong doc page

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
aaaaah thanks so much!

**Comment by FBruzzesi** [comment]
Edit: Not sure if this was intended to be under api-reference (arguably not the best place to find it?!) - yet it is there and the link was another page

**Comment by FBruzzesi** [comment]
Double Edit: Marco is just to fast to merge 😂

**Comment by MarcoGorelli** [comment]
> Second edit: Marco is just to fast to merge 😂

😄 ah sorry! idk, I think it's part of the api in the sense that you can do `from narwhals.typing import ...` - but maybe it could be better placed somewhere else?

**Comment by FBruzzesi** [comment]
> I think it's part of the api in the sense that you can do `from narwhals.typing import ...`

Then let's keep it there :)

**Pull request merged**
