### PR TITLE
feat: pyarrow dataframe `iter_rows`

### PR DESCRIPTION
**Pull request by aidoskanapyanov**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #372 

## Checklist

- [x] Code follows style guide (ruff)
- [x] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by aidoskanapyanov** [comment]
@MarcoGorelli I found some open issues on arrow's repo that seem to be related to this https://github.com/apache/arrow/issues/28694 https://github.com/apache/arrow/issues/28689. They mention currently there is no really efficient way to iterate over rows.

Although one of them has a snippet with suggestion on how to implement `itertuples` might be useful https://github.com/apache/arrow/issues/28689#issuecomment-1378027972

**Comment by FBruzzesi** [comment]
There _may_ be a way using column buffers, I didn't have the time to investigate fully 🙈

**Comment by MarcoGorelli** [comment]
thanks - i think the suggestion looks good

**Comment by aidoskanapyanov** [comment]
@MarcoGorelli I added some changes to use buffer_size and yield from slice of pyarrow table and limit memory usage.

**Review by MarcoGorelli — APPROVED** [review]
awesome, thanks @aidoskanapyanov !

**Comment by FBruzzesi** [comment]
How did this pass the `check_backend_completeness.py` check?! 👀

**Pull request merged**
