### PR TITLE
docs: Use `IntoDataFrame` in docs

### PR DESCRIPTION
**Pull request by luke396**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue #386
- Closes #

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks @luke396 ! I think these ones are fine, I was thinking more about using these type hints in the docstrings

**Comment by luke396** [comment]
> thanks @luke396 ! I think these ones are fine, I was thinking more about using these type hints in the docstrings

Ah, I notice some differences between the user guide/tutorial and the docstring. Are the changes in the tutorial necessary? If so, I'd like to make further modifications; if not, closing the PR is perfectly acceptable.

Regarding the `IntoDataFrame` and `IntoDataFrameT` in the method's docstring, I plan to look into them later.

**Comment by MarcoGorelli** [comment]
I think the tutorial is probably the first thing that a lot of people will see, so improving it is certainly a good idea 👍 If there are places in the tutorial which don't have type annotations, then I think adding them would be beneficial

**Comment by luke396** [comment]
Absolutely, adding type annotations where they're missing is a great idea.

I'm slightly confused about other type annotations, especially those changed in the current PR. To be honest, I'm not entirely sure which ones to use in the tutorial. I've read their definitions, and it seems they have some inclusion relationships or minor differences in certain subtypes. So, which one to choose is a question.

My question is, should we update them in the tutorial based on a specific principle? Or have we already settled on annotations, and I've just missed something?

**Pull request closed without merging**
