### PR TITLE
fix: make Series.scatter always return new series

### LINKED ISSUE #1154: [Enh]: `Series.scatter()` should always return a new `Series`
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

posit-dev/py-shiny

### Please describe the purpose of the new feature or describe the problem to solve.

From [docs](https://github.com/narwhals-dev/narwhals/blob/b961d4eb982b945fcd8efb84f896c275086296c0/narwhals/series.py#L145-L150):
> For some libraries (pandas, Polars), this method operates in-place, whereas for others (PyArrow) it doesn't! We recommend being careful with it, and not relying on the in-placeness. For example, a valid use case is when updating a column in an eager dataframe, see the example below.

I'd like for this behavior to be consistent: use copy on write to return a new Series

Pandas is moving towards copy on write by default in pandas v3. 

When using narwhals's .scatter method, it currently displays a warning about enabling copy on write by default for pandas v2.
```
/venv/lib/python3.12/site-packages/narwhals/_pandas_like/series.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s.iloc[indices] = values
```
[link to related code](https://github.com/narwhals-dev/narwhals/blob/b961d4eb982b945fcd8efb84f896c275086296c0/narwhals/_pandas_like/series.py#L190)

### Suggest a solution if possible.

Change the return type of `.scatter()` to return a new `nw.Series` object.

For pandas, call `pd.options.mode.copy_on_write = True` to enable copy on write today to avoid problems later. 

For polars, update the code to return a new pl.Series object.

### If you have tried alternatives, please describe them below.

Adding `pd.options.mode.copy_on_write = True` line within pandas like `.scatter()` made the warning disappear and gave me expected behavior of a new series. 

I understand this is not a generic solution for pandas-like.

I'm currently getting around it by calling `nw_data = nw_data.clone()` before updating its Series values with `.scatter()`. 

### Additional information that may help us understand your needs.

_No response_

### PR DESCRIPTION
**Pull request by Cheukting**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- closes #1154 
- Closes #1154

## Checklist

- [X] Code follows style guide (ruff)
- [X] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by Cheukting** [comment]
@MarcoGorelli all check passes! This is a joint PR with @marcoala at the sprint

**Review by MarcoGorelli — COMMENTED** [review]
this is wonderful, thanks @Cheukting and @marcoala!

could you also include a test which checks
```
s = df['a']
s.scatter({'a': [1, 2, 3]})
compare_dicts({'a': s}, expected
```
please? just to check that even with a free-standing series, things don't get modified

**Comment by Cheukting** [comment]
Good catch @MarcoGorelli I have added the test and fix polars behaviour (we were wondering why polars didn't fail the test and now we know)

**Review by MarcoGorelli — APPROVED** [review]
thanks so much both!

i just added a commit to also address the other issue you noticed (thanks so much for reporting it!)

note that you can use `extract_native` instead of calling `to_list` - `to_list` creates a Python list, which can be inefficient, whereas `extract_native` extracts the native Polars Series from a Narwhals PolarsSeries object

**Pull request merged**
