### PR TITLE
narwhals-gif README.md

### PR DESCRIPTION
**Pull request by anopsy**
Sorry for making it a separate PR but I didn't know how to turn the gif into github-asset other than just droping it in the README.md (and didn't want to experiment with branches on github)
Does this looks now more clear and comprehensible?
Do you like the white background? I feel like it looks better in the README.md but if anybody what's back the cotton-candy-theme let me know.

## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [x] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Related issues 

- Related issue # 
- Closes #

## Checklist

- [ ] Code follows style guide (ruff)
- [ ] Tests added 
- [ ] Documented the changes

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
love this, we're lucky to have you! 😍 

really minor, but it looks like the order now goes: pandas, rapids, polars, pandas. So, watching it in a loop results in pandas being visited twice in a row?

**Comment by anopsy** [comment]
weird but indeed, let me fix that then, I'm afraid I'll have to do again a separate PR , I hope you don't mind

**Review by MarcoGorelli — APPROVED** [review]
❤️ love this

ready to merge?

**Comment by anopsy** [comment]
yeah let's go

**Pull request merged**
